use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :miniprojet, GothamWeb.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"} || 4000],
  check_origin: false,
  server: true,
  root: ".",
  secret_key_base: {:system, "SECRET_KEY_BASE"}

config :miniprojet, Gotham.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "7pGd94CGu6n3B9BH",
  database: "gotham",
  socket_dir: "/tmp/cloudsql/gotham-254312:europe-west1:gotham-db-instance",
  pool_size: 20
  # ssl: true


# Do not print debug messages in production
config :logger, level: :info

# Configure your database

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :miniprojet, GothamWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :miniprojet, GothamWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
# import_config "prod.secret.exs"
